task: seg
num_classes: 11
ignore_index: 255
seed: 42
model:
  name: spectralgpt
  kwargs:
    num_frames: 3
    num_classes: 11
    img_size: 128
    decoder_channels: 256
    pretrained_backbone: true
    pretrained_backbone_path: pretrained_weight/SpectralGPT+.pth
dataset:
  name: rescuenet
  train:
    dataset_path: data/infra_damage/rescuenet/train_crop
    data_list_path: data/infra_damage/rescuenet/train_crop_tiles.txt
    crop_size: 128
    split: train
  val:
    dataset_path: data/infra_damage/rescuenet/val_crop
    data_list_path: data/infra_damage/rescuenet/val_crop_tiles.txt
    crop_size: null
    split: val
  test:
    dataset_path: data/infra_damage/rescuenet/test_crop
    data_list_path: data/infra_damage/rescuenet/test_crop_tiles.txt
    crop_size: null
    split: test
augmentation:
  train:
    SmartCrop:
      crop_size: 128
      cat_max_ratio: 0.75
      max_retry: 50
      ignore_index: 255
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 1.0
    Normalize:
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
      max_pixel_value: 1.0
  val:
    Normalize:
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
      max_pixel_value: 1.0
optimizer:
  name: AdamW
  learning_rate: 5.0e-06
  weight_decay: 0.01
scheduler:
  name: null
loss:
  use_lovasz: true
  lovasz_weight: 0.75
training:
  num_epochs: 30
  train_batch_size: 32
  eval_batch_size: 1
  num_workers: 32
  eval_interval: 2000
output_dir: ./results/rescuenet/spectralgpt
inference:
  sliding_kernel: 128
  sliding_stride: 64
