task: cd
num_classes: 2
ignore_index: 255
seed: 42
model:
  name: samdpt
  kwargs:
    in_channels: 6
    num_classes: 2
    sam_type: vit_l
    sam_checkpoint: pretrained_weight/sam_vit_l_0b3195.pth
    decoder_channels: 256
    head_channels: 256
    hook_indices:
    - 5
    - 11
    - 17
    - 23
    num_features: 4
dataset:
  name: gvlm
  train:
    dataset_path: data/landslides/GVLM_CD
    data_list_path: data/landslides/GVLM_CD/train.txt
    crop_size: 512
    split: train
  val:
    dataset_path: data/landslides/GVLM_CD
    data_list_path: data/landslides/GVLM_CD/val.txt
    crop_size: null
    split: val
  test:
    dataset_path: data/landslides/GVLM_CD
    data_list_path: data/landslides/GVLM_CD/test.txt
    crop_size: null
    split: test
augmentation:
  train:
    Normalize: &id001
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
      max_pixel_value: 1.0
      always_apply: true
  val:
    Normalize: *id001
optimizer:
  name: AdamW
  learning_rate: 5.0e-05
  weight_decay: 0.0001
scheduler:
  name: StepLR
  step_size: 2000
  gamma: 0.8
training:
  num_epochs: 100
  train_batch_size: 16
  eval_batch_size: 16
  num_workers: 16
  eval_interval: 300
output_dir: ./results/gvlm/cd_samdpt
