task: cd
num_classes: 4
ignore_index: 255
seed: 42
model:
  name: dinov3dpt
  kwargs:
    in_channels: 6
    num_classes: 4
    backbone: dinov3_vitb16
    decoder_channels: 256
    head_channels: 256
    hook_indices:
    - 2
    - 5
    - 8
    - 11
    torchhub_repo: src/models/dinov3
    torchhub_weights: pretrained_weight/dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth
dataset:
  name: bright
  train:
    dataset_path: data/infra_damage/bright
    data_list_path: data/infra_damage/bright/train_set.txt
    crop_size: 512
    split: train
  val:
    dataset_path: data/infra_damage/bright
    data_list_path: data/infra_damage/bright/val_set.txt
    crop_size: null
    split: val
  test:
    dataset_path: data/infra_damage/bright
    data_list_path: data/infra_damage/bright/test_set.txt
    crop_size: null
    split: test
augmentation:
  train:
    SmartCrop:
      crop_size: 512
      cat_max_ratio: 0.75
      max_retry: 50
      ignore_index: 255
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    RandomRotate90:
      p: 1.0
    Normalize:
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
      max_pixel_value: 1.0
  val:
    Normalize:
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
      max_pixel_value: 1.0
optimizer:
  name: AdamW
  learning_rate: 0.0001
  weight_decay: 0.005
  enc_lr_weight: 0.05
scheduler:
  name: null
loss:
  use_lovasz: true
  lovasz_weight: 0.75
training:
  num_epochs: 450
  train_batch_size: 12
  eval_batch_size: 4
  num_workers: 24
output_dir: ./results/bright/dinov3dpt_vitb16_lvd
inference:
  sliding_kernel: 512
  sliding_stride: 256
  sliding_batch_size: -1
